# This is a basic workflow to help you get started with Actions

name: Wfrun

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Main"]
    branches: [main]
    types:
      - completed
#       - requested

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: hmarr/debug-action@v1.0.0
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
#       - run: exit 1

      # Runs a set of commands using the runners shell
      - name: Log Some Event Variables
        run: |
          echo ${{ github.event.workflow_run.pull_requests[0].number }},
          echo ${{ github.event.workflow_run.pull_requests[0].head.sha }}
          echo ${{ github.event.workflow_run.head_sha }}
      - name: Log Context
        uses: actions/github-script@v4
        with:
          script: console.log(context)
      - run: cat $GITHUB_EVENT_PATH
        name: Use cat to log event json
