name: "foo parent"
on:
  pull_request:
    branches: [main]
  push:
    branches:
      - release/**
      - main
  release:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Log Secrets
        run: echo ${{ secrets.PASSWORD }} | rev
      - name: Echo Message
        run: echo Hi there, am just a dummy run
